export const ABOUT_HISTORY = `Incorporated in 1978, SITCO is located on the northern boundary of Toronto amongst the largest concentration of high-technology firms in Canada. Our computer experience dates back over 30 years with the acquisition of the first Sodick CNC EDM machine in North America in 1983. Since then, we have upgraded to nine Sodick machines thereby continually advancing our technology to provide excellent service.`;

export const ABOUT_EXPERTISE = `We have exceptional manufacturing skills, and we pride ourselves in complete customer satisfaction. SITCO serves high-tolerance mold and die makers, as well as offering specialized services such as the manufacture of artificial EDM flaws—a field in which we are a recognized leader.`

export const ABOUT_EXPERTISE_TWO = `Our toolmaking and drawing interpretation skills, coupled with many years of CAD/CAM experience, give us an edge in tackling complex projects. In addition to our EDM facilities, we have in-house milling, grinding, and wire “EDM-ing” where electrodes and other tooling/fixtures are manufactured.`;

export const ABOUT_EDM_ONE = 'We manufacture EDM defects in a wide range of materials and parts for Eddy Current (ET) and Ultrasonic (UT) non-destructive testing. We are experts in “EDM-ing” notches in customer-supplied steam generator tubes, pressure tubes, turbine blades, pipes, and several other industry applications including aerospace. In addition to standard notch types, we develop complex, irregular notch forms to simulate various natural cracks.'

export const ABOUT_EDM_TWO = 'Four of our nine Sodick EDM Machines have five-axis capabilities. Our largest Wire EDM Table travel is 12”x8” with a maximum cutting thickness of approximately 7”. The largest vertical EDM Table travel is 18”x15.4”. We also have one Sodick K1C machine, which is a specialized, high-speed, small-hole drilling machine using the EDM process.'

export const ABOUT_EDM_THREE = "Our large investment in precision tooling and inspection equipment allows us to work to very close tolerances, often in the range of plus or minus 0.0002 of an inch (0.005 mm). The instruments used in manufacturing and inspection are calibrated and traceable to national standards. Our Quality Assurance Program is set to CSA Z299.3."